chaos: fix thread error handling
Threads return `Result<ThreadReturnValue, ...>` when joined in Rust.
chaos threads therefore return `Result<Result<Y, ...>>` when joined, and
it's only handling the outer one. This means the inner error gets
silently dropped. Fix this by handling the outer error with
`panic::resume_unwind`, and returning the inner Error if there is one.

Test plan:

Before:
```
jake@rooster:/data/users/jake/repos/scx/ > cargo build --release -p scx_chaos && sudo target/release/scx_chaos
warning: /data/users/jake/repos/scx/rust/scx_rustland_core/Cargo.toml: unused manifest key: lib.include
warning: /data/users/jake/repos/scx/Cargo.toml: unused manifest key: profile.release-fast.debuginfo
warning: /data/users/jake/repos/scx/Cargo.toml: unused manifest key: profile.release-fast.target-cpu
   Compiling scx_utils v1.0.16 (/data/users/jake/repos/scx/rust/scx_utils)
   Compiling scx_p2dq v1.0.17 (/data/users/jake/repos/scx/scheds/rust/scx_p2dq)
   Compiling scx_userspace_arena v1.0.13 (/data/users/jake/repos/scx/rust/scx_userspace_arena)
   Compiling scx_chaos v1.0.16 (/data/users/jake/repos/scx/scheds/rust/scx_chaos)
    Finished `release` profile [optimized] target(s) in 2m 36s
13:12:19 [INFO] Builder { traits: [], verbose: 0, p2dq_opts: SchedulerOpts { disable_kthreads_local: false, autoslice: false, interactive_ratio: 10, deadline: false, eager_load_balance: false, freq_control: false, greedy_idle_disable: true, interactive_sticky: false, interactive_fifo: false, dispatch_pick2_disable: false, dispatch_lb_busy: 75, dispatch_lb_interactive: false, keep_running: false, wakeup_lb_busy: 0, wakeup_llc_migrations: false, select_idle_in_enqueue: false, idle_resume_us: None, max_dsq_pick2: false, min_slice_us: 100, lb_slack_factor: 5, min_llc_runs_pick2: 3, dsq_time_slices: [], dsq_shift: 4, min_nr_queued_pick2: 0, dumb_queues: 3, init_dsq_index: 0 }, requires_ppid: None }
13:12:19 [INFO] DSQ[0] slice_ns 100000
13:12:19 [INFO] DSQ[1] slice_ns 3200000
13:12:19 [INFO] DSQ[2] slice_ns 6400000
13:12:19 [INFO] libbpf: struct_ops chaos: member priv not found in kernel, skipping it as it's set to zero

13:12:19 [WARN] libbpf: prog 'scx_bitmap_from_bpf': relo #20: insn #8 (LDX/ST/STX) accesses field incorrectly. Make sure you are accessing pointers, unsigned integers, or fields of matching type and size.
```

After:
```
jake@rooster:/data/users/jake/repos/scx/ > cargo build --release -p scx_chaos && sudo target/release/scx_chaos
warning: /data/users/jake/repos/scx/Cargo.toml: unused manifest key: profile.release-fast.debuginfo
warning: /data/users/jake/repos/scx/Cargo.toml: unused manifest key: profile.release-fast.target-cpu
warning: /data/users/jake/repos/scx/rust/scx_rustland_core/Cargo.toml: unused manifest key: lib.include
   Compiling scx_utils v1.0.16 (/data/users/jake/repos/scx/rust/scx_utils)
   Compiling scx_p2dq v1.0.17 (/data/users/jake/repos/scx/scheds/rust/scx_p2dq)
   Compiling scx_userspace_arena v1.0.13 (/data/users/jake/repos/scx/rust/scx_userspace_arena)
   Compiling scx_chaos v1.0.16 (/data/users/jake/repos/scx/scheds/rust/scx_chaos)
    Finished `release` profile [optimized] target(s) in 2m 35s
13:09:05 [INFO] Builder { traits: [], verbose: 0, p2dq_opts: SchedulerOpts { disable_kthreads_local: false, autoslice: false, interactive_ratio: 10, deadline: false, eager_load_balance: false, freq_control: false, greedy_idle_disable: true, interactive_sticky: false, interactive_fifo: false, dispatch_pick2_disable: false, dispatch_lb_busy: 75, dispatch_lb_interactive: false, keep_running: false, wakeup_lb_busy: 0, wakeup_llc_migrations: false, select_idle_in_enqueue: false, idle_resume_us: None, max_dsq_pick2: false, min_slice_us: 100, lb_slack_factor: 5, min_llc_runs_pick2: 3, dsq_time_slices: [], dsq_shift: 4, min_nr_queued_pick2: 0, dumb_queues: 3, init_dsq_index: 0 }, requires_ppid: None }
13:09:05 [INFO] DSQ[0] slice_ns 100000
13:09:05 [INFO] DSQ[1] slice_ns 3200000
13:09:05 [INFO] DSQ[2] slice_ns 6400000
13:09:05 [INFO] libbpf: struct_ops chaos: member priv not found in kernel, skipping it as it's set to zero

13:09:05 [WARN] libbpf: prog 'scx_bitmap_from_bpf': relo #20: insn #8 (LDX/ST/STX) accesses field incorrectly. Make sure you are accessing pointers, unsigned integers, or fields of matching type and size.

Error: another sched_ext scheduler is already running
```