scxtest: fix undeclared reallocarray() with old glibc
Building scx on a machine with glibc 2.28 breaks like so:

  $ cargo build --release
  ...
  lib/scxtest/scx_test_map.c:43:18: error: call to undeclared function 'reallocarray'
  ...
    43 |         scx_map_types = reallocarray(scx_map_types, scx_map_types_count,

glibc2.28 has reallocarray() but it's necessary to define the feature
test macro _GNU_SOURCE.  Do it to fix the build on OL8/RHEL8.

Signed-off-by: Daniel Jordan <daniel.m.jordan@oracle.com>