utils: Graceful error handling for EnergyModel.
When debugfs is not mounted (or disabled), creating EnergyModel caused
a panic with the following error:

  thread 'main' (465) panicked at rust/scx_utils/src/energy_model.rs:237:44:
  called `Result::unwrap()` on an `Err` value: No debugfs mount found

Instead of unwrap(), let's use ? to propagate an error, so handling it
gracefully without panicking.

Signed-off-by: Changwoo Min <changwoo@igalia.com>