scx_arena: prepare crate for publishing
`scx_arena` tries to reach out of its crate for the `lib` symlink. This
doesn't work when publishing the crate and we need to publish it as part
of the next release.

Put the `lib` symlink under `src/bpf` to match the other crates. Do the
same for the selftests - this isn't necessary, but we might as well be
uniform.

Test plan:
- CI

Before:
```
jake@merlin:/data/users/jake/repos/scx/ > cargo publish --dry-run -p scx_arena
...
error: failed to run custom build command for `scx_arena v0.1.0 (/data/users/jake/repos/scx/target/package/scx_arena-0.1.0)`

Caused by:
  process didn't exit successfully: `/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-bf64fdc95843afec/build-script-build` (exit status: 101)
  --- stdout
  scx_utils:clang=ClangInfo { clang: "/nix/store/0si2lspdxwjdlj2qba32pyq8xqyxwyyl-bpf-clang-19.1.7/bin/clang", ver: "19.1.7", arch: "x86_64" } ["-g", "-O2", "-Wall", "-Wno-compare-distinct-pointer-types", "-D__TARGET_ARCH_x86", "-mcpu=v3", "-mlittle-endian", "-idirafter", "/nix/store/10mkp77lmqz8x2awd8hzv6pf7f7rkf6d-clang-19.1.7-lib/lib/clang/19/include", "-idirafter", "/nix/store/36z1pi36yz08f1k7zgs9kxrx2zskrbv1-linux-headers-6.17.0-rc1/usr/include", "-idirafter", "/nix/store/gf3wh0x0rzb1dkx0wx1jvmipydwfzzd5-glibc-2.40-66-dev/include", "-I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h/arch/x86", "-I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h", "-I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h/bpf-compat"]

  --- stderr

  thread 'main' panicked at build.rs:20:10:
  called `Result::unwrap()` on an `Err` value: failed to build `../lib/arena.bpf.c`

  Caused by:
      0: failed to compile `../lib/arena.bpf.c`
      1: failed to compile /tmp/nix-shell.RJiktV/.tmpPb0sie/arena.bpf.c from ../lib/arena.bpf.c
      2: command `/nix/store/0si2lspdxwjdlj2qba32pyq8xqyxwyyl-bpf-clang-19.1.7/bin/clang -g -O2 -Wall -Wno-compare-distinct-pointer-types -D__TARGET_ARCH_x86 -mcpu=v3 -mlittle-endian -idirafter /nix/store/10mkp77lmqz8x2awd8hzv6pf7f7rkf6d-clang-19.1.7-lib/lib/clang/19/include -idirafter /nix/store/36z1pi36yz08f1k7zgs9kxrx2zskrbv1-linux-headers-6.17.0-rc1/usr/include -idirafter /nix/store/gf3wh0x0rzb1dkx0wx1jvmipydwfzzd5-glibc-2.40-66-dev/include -I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h/arch/x86 -I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h -I/data/users/jake/repos/scx/target/package/scx_arena-0.1.0/target/debug/build/scx_arena-01d388b0bd6c0ec8/out/scx_utils-bpf_h/bpf-compat -I /tmp/nix-shell.RJiktV/.tmpxX9PHf/bpf/src -fno-stack-protector -g -O2 -target bpf -c ../lib/arena.bpf.c -o /tmp/nix-shell.RJiktV/.tmpPb0sie/arena.bpf.c` failed (exit status: 1)
      3: clang: error: no such file or directory: '../lib/arena.bpf.c'
         clang: error: no input files

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to verify package tarball
```

After:
```
jake@merlin:/data/users/jake/repos/scx/ > cargo publish --dry-run -p scx_arena
...
   Compiling scx_arena v0.1.0 (/data/users/jake/repos/scx/target/package/scx_arena-0.1.0)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 35.77s
   Uploading scx_arena v0.1.0 (/data/users/jake/repos/scx/rust/scx_arena/scx_arena)
warning: aborting upload due to dry run
```