scx_cake: Downgrade sysinfo dependency
scx_cake currently rewquires sysinfo >= 0.39, which in turn requires
rustc >= 1.95. This breaks builds on Ubuntu 24.04, where the newest
rustc version currently available in the distro is 1.91:

 error: rustc 1.91.1 is not supported by the following package:
  sysinfo@0.39.1 requires rustc 1.95

scx_cake does not rely on any specific features introduced in sysinfo
0.39, so downgrade the dependency to 0.38 to restore compatibility with
Ubuntu.

Signed-off-by: Andrea Righi <arighi@nvidia.com>