scx_rustland_core: Fix char type on arm64
Commit beab2f38 ("scx_rustland_core: Introduce QueuedTask:comm_str()")
introduced the following build error on arm64:

error[E0308]: mismatched types
   --> scheds/rust/scx_rustland/src/bpf.rs:167:19
    |
167 |             comm: self.inner.comm,
    |                   ^^^^^^^^^^^^^^^ expected `[i8; 16]`, found `[u8; 16]`
    |
    = note: expected array `[i8; 16]`
               found array `[u8; 16]`

Fix by declaring comm as an array of c_char elements, instead of i8,
ensuring portability across different architectures.

Fixes: beab2f38 ("scx_rustland_core: Introduce QueuedTask:comm_str()")
Signed-off-by: Andrea Righi <arighi@nvidia.com>