scx_nest: Remove dependency of sdt_task.h
scx_nest is not using anything from sdt_task.h, so drop this include.

This fixes the following build error:

 libbpf: elf: sec '.addr_space.1': to use global __arena variables the ARENA map should be explicitly declared in SEC(".maps")
 Error: failed to open BPF object file: No such file or directory

Fixes: 81fbddc1 ("lib: introduce arena-backed stack for allocations")
Signed-off-by: Andrea Righi <arighi@nvidia.com>