cargo: Downgrade sysinfo to 0.38
Ubuntu 24.04 provides rustc up to 1.91, which fails to build sysinfo:

  error: rustc 1.91.1 is not supported by the following package:
    sysinfo@0.39.1 requires rustc 1.95

Downgrade sysinfo dependency to 0.38 to prevent the build failures and
properly support Ubuntu 24.04.

Signed-off-by: Andrea Righi <arighi@nvidia.com>