include/scx: introduce struct qspinlock
Port kernel commit 1f375aef6cc0 ("selftests/bpf: Fix arena_spin_lock
compilation on PowerPC") and commit be5521991506 ("selftests/bpf: Fix
endianness issue in __qspinlock declaration") in order to fix

    error: incomplete definition of type '__arena struct qspinlock'

on s390.

Signed-off-by: Ilya Leoshkevich <iii@linux.ibm.com>